name: pointer_gnn
source: huggingface
repo_type: model
repo_id: jajostrains/Mathlib-Sexpr-GNN
revision: 53ccfea5927d70286a5211ae6936ead9db69f70a
subfolder: pointer-gat-gru
local_subdir: maths_ai/gnn_inference/models/mathlib_sexpr_gnn
